//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflectra.Rapise.RapiseLauncher.Branding.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inflectra.Rapise.RapiseLauncher.Branding.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches Rapise automated tests on this host based on the schedule managed in SpiraTest.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Rapise Launcher.
        /// </summary>
        public static string App_AboutFormName {
            get {
                return ResourceManager.GetString("App_AboutFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapise.
        /// </summary>
        public static string App_AutomationToken {
            get {
                return ResourceManager.GetString("App_AutomationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (C) Copyright Inflectra Corporation 2006-2011.
        /// </summary>
        public static string App_CompanyCopyright {
            get {
                return ResourceManager.GetString("App_CompanyCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflectra.
        /// </summary>
        public static string App_CompanyName {
            get {
                return ResourceManager.GetString("App_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to SpiraTest Server.
        /// </summary>
        public static string App_ErrorConnecting {
            get {
                return ResourceManager.GetString("App_ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapise Launcher.
        /// </summary>
        public static string App_FullName {
            get {
                return ResourceManager.GetString("App_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://inflectra.com/Documents/SpiraTest-Team%20RemoteLaunch%20Automated%20Testing%20User%20Guide.pdf.
        /// </summary>
        public static string App_HelpPDFURL {
            get {
                return ResourceManager.GetString("App_HelpPDFURL", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap App_Logo {
            get {
                object obj = ResourceManager.GetObject("App_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoError_Lg {
            get {
                object obj = ResourceManager.GetObject("icoError_Lg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoExit {
            get {
                object obj = ResourceManager.GetObject("icoExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoForce {
            get {
                object obj = ResourceManager.GetObject("icoForce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoHelp {
            get {
                object obj = ResourceManager.GetObject("icoHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoPause {
            get {
                object obj = ResourceManager.GetObject("icoPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoPaused_Lg {
            get {
                object obj = ResourceManager.GetObject("icoPaused_Lg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoPoll_Lg {
            get {
                object obj = ResourceManager.GetObject("icoPoll_Lg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoResume {
            get {
                object obj = ResourceManager.GetObject("icoResume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoRunning_Lg {
            get {
                object obj = ResourceManager.GetObject("icoRunning_Lg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoSettings {
            get {
                object obj = ResourceManager.GetObject("icoSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icoTesting_Lg {
            get {
                object obj = ResourceManager.GetObject("icoTesting_Lg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resStatusError {
            get {
                object obj = ResourceManager.GetObject("resStatusError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resStatusFinished {
            get {
                object obj = ResourceManager.GetObject("resStatusFinished", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resStatusNone {
            get {
                object obj = ResourceManager.GetObject("resStatusNone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resStatusRunning {
            get {
                object obj = ResourceManager.GetObject("resStatusRunning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon Server {
            get {
                object obj = ResourceManager.GetObject("Server", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpiraTest.
        /// </summary>
        public static string Server_ProductName {
            get {
                return ResourceManager.GetString("Server_ProductName", resourceCulture);
            }
        }
    }
}
