//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflectra.Rapise.RapiseLauncher.UserInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inflectra.Rapise.RapiseLauncher.UserInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application?
        ///Without the application running, no tests will be executed..
        /// </summary>
        internal static string App_AreYouSureToExit {
            get {
                return ResourceManager.GetString("App_AreYouSureToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string App_AreYouSureToExitHeader {
            get {
                return ResourceManager.GetString("App_AreYouSureToExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot run a manual test when an automated test is already executing..
        /// </summary>
        internal static string App_CannotRunManualTest {
            get {
                return ResourceManager.GetString("App_CannotRunManualTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Run Test.
        /// </summary>
        internal static string App_CannotRunTest {
            get {
                return ResourceManager.GetString("App_CannotRunTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server could not be contacted to retrieve test information.
        ///Please go into the settings and verify the server and user information, then run the test file again..
        /// </summary>
        internal static string App_ConnectToServerError {
            get {
                return ResourceManager.GetString("App_ConnectToServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string App_Error {
            get {
                return ResourceManager.GetString("App_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Opening Site.
        /// </summary>
        internal static string App_ErrorLaunchingBrowser {
            get {
                return ResourceManager.GetString("App_ErrorLaunchingBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not launch URL. You can find the documentation online at:
        ///{0}.
        /// </summary>
        internal static string App_ErrorLaunchingBrowserMessage {
            get {
                return ResourceManager.GetString("App_ErrorLaunchingBrowserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Configuration Settings.
        /// </summary>
        internal static string App_InvalidConfiguration {
            get {
                return ResourceManager.GetString("App_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s configuration is not set properly. Please go to the Client Setup tab to correct..
        /// </summary>
        internal static string App_InvalidConfigurationMessage {
            get {
                return ResourceManager.GetString("App_InvalidConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Configuration.
        /// </summary>
        internal static string App_NotifyIconMenuConfig {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Configuration and Status window..
        /// </summary>
        internal static string App_NotifyIconMenuConfigTooltip {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string App_NotifyIconMenuExit {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuts down the application..
        /// </summary>
        internal static string App_NotifyIconMenuExitTooltip {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuExitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string App_NotifyIconMenuHelp {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string App_NotifyIconMenuHelpAbout {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays application and loaded plugin information..
        /// </summary>
        internal static string App_NotifyIconMenuHelpAboutTooltip {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuHelpAboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string App_NotifyIconMenuHelpTooltip {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View Help.
        /// </summary>
        internal static string App_NotifyIconMenuHelpView {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuHelpView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the application&apos;s Help..
        /// </summary>
        internal static string App_NotifyIconMenuHelpViewTooltip {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuHelpViewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string App_NotifyIconMenuPause {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses polling of events and execution of scheduled tests..
        /// </summary>
        internal static string App_NotifyIconMenuPauseTooltip {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuPauseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Poll Now.
        /// </summary>
        internal static string App_NotifyIconMenuPollnow {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuPollnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force a poll now for any scheduled tests..
        /// </summary>
        internal static string App_NotifyIconMenuPollnowTooltip {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuPollnowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resume.
        /// </summary>
        internal static string App_NotifyIconMenuResume {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumes polling of events and execution of scheduled tests..
        /// </summary>
        internal static string App_NotifyIconMenuResumeTooltip {
            get {
                return ResourceManager.GetString("App_NotifyIconMenuResumeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next update in {0}.
        /// </summary>
        internal static string App_NotifyIconStatusNextUpdate {
            get {
                return ResourceManager.GetString("App_NotifyIconStatusNextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is Paused.
        /// </summary>
        internal static string App_NotifyIconStatusPaused {
            get {
                return ResourceManager.GetString("App_NotifyIconStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Test Schedule....
        /// </summary>
        internal static string App_NotifyIconStatusPolling {
            get {
                return ResourceManager.GetString("App_NotifyIconStatusPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is minimized, and will automatically scan for requests for tests on this system..
        /// </summary>
        internal static string App_NotifyIconWelcomeText {
            get {
                return ResourceManager.GetString("App_NotifyIconWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Test:.
        /// </summary>
        internal static string App_RunningTest {
            get {
                return ResourceManager.GetString("App_RunningTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server specified in the test file is different than the one currently configured.
        ///Please go into the settings and correct the server information, then run the test file again..
        /// </summary>
        internal static string App_ServerErrorMessage {
            get {
                return ResourceManager.GetString("App_ServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to the SpiraTeam server..
        /// </summary>
        internal static string Config_ServerSettings_ConnectedSucceeded {
            get {
                return ResourceManager.GetString("Config_ServerSettings_ConnectedSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the server ({0}).
        /// </summary>
        internal static string Config_ServerSettings_ConnectionFailed {
            get {
                return ResourceManager.GetString("Config_ServerSettings_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL specified is not valid.
        /// </summary>
        internal static string Config_ServerSettings_InvalidUrl {
            get {
                return ResourceManager.GetString("Config_ServerSettings_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL specified should not include the .aspx part of the URL.
        /// </summary>
        internal static string Config_ServerSettings_UrlNotIncludeLogin {
            get {
                return ResourceManager.GetString("Config_ServerSettings_UrlNotIncludeLogin", resourceCulture);
            }
        }
    }
}
